_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 50
                - 55
            "2":
                - 50
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.11.8
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": darwin-arm64
constraints:
    value:
        dist_other_gs: 500000
debug:
    value:
        plot: false
        verbose: true
end_epoch:
    value:
        day: 21
        hour: 0
        minute: 0
        month: 5
        second: 0
        year: 2024
problem:
    value:
        gs_num: 1
        method: nelder
        objective: maximize_contact_seconds
        sat_num: 1
        type: free
scenario:
    value:
        constellations: ICEYE
        teleport_sites: null
start_epoch:
    value:
        day: 20
        hour: 0
        minute: 0
        month: 5
        second: 0
        year: 2024
wandb:
    value:
        entity: loc_gsopt
