# Config files for problem setup and formulation
# Can input the following:
#     - Problem Scope
#         - type of problem (free or teleport selection)
#         - Solution method
#         - of sites to select
#     - Scenario Development:
#         - previous sites & locations (if teleport problem)
#         - Satellite list
#         - List of candidate sites for teleports
#         - start and end epochs 
# Output of selected sites

wandb:
  entity: "loc_gsopt"

problem:
  #type: "free"
  type: "teleport"
  method: "nelder" # TODO: add options for other methods 
                        # make sure you can only choose appropriate
                        # methods for appropriate problem types
  objective: "data_downlink" #data_downlink, gap_optimization, max_contacts
  gs_num: 5
  teleport_num: 10
  sat_num: 5 # Start with 10, just to not overload the solver
  data_rate: 10 # Mbps

scenario:
  constellations: "ICEYE" # 'YAM', 'UMBRA', 'SKYSAT', 'ICEYE', 
                          #'FLOCK', 'HAWK', 'CAPELLA', 'LEGION', 
                          #'WORLDVIEW', 'GEOEYE', 'NUSAT'
  start_simplex: 1 # can be 0-6
  teleport_sites:
    # TODO: Need to add teleport functionality, list of sites to select
  
constraints:
  dist_other_gs: 500000 # 500 km

start_epoch:
  year: 2024
  month: 5
  day: 20
  hour: 0
  minute: 0
  second: 0

end_epoch:
  year: 2024
  month: 5
  day: 21
  hour: 0
  minute: 0
  second: 0

debug:
  verbose: True
  plot: True
