# Config files for problem setup and formulation
# Can input the following:
#     - Problem Scope
#         - type of problem (free or teleport selection)
#         - Solution method
#         - of sites to select
#     - Scenario Development:
#         - previous sites & locations (if teleport problem)
#         - Satellite list
#         - List of candidate sites for teleports
#         - start and end epochs 
# Output of selected sites

wandb:
  entity: "loc_gsopt"

problem:
  #type: "free"
  type: "teleport"
  method: "nelder" # TODO: add options for other methods 
                        # make sure you can only choose appropriate
                        # methods for appropriate problem types
  objective: "gap_optimization" #data_downlink, gap_optimization, max_contacts
  gs_num: 5
  teleport_num: 10
  sat_num: 1 # Start with 10, just to not overload the solver
  data_rate: 1200000000 # bps

scenario:
  constellations: "UMBRA" # 'YAM', 'UMBRA', 'SKYSAT', 'ICEYE', 
                          #'FLOCK', 'HAWK', 'CAPELLA', 'LEGION', 
                          #'WORLDVIEW', 'GEOEYE', 'NUSAT'
  start_simplex: 3 # can be 0-6, random
  datarate: 1200000000.0 # Data Rate [bps], for now, just set to this for all satellites and ground stations
  teleport_sites:
    # TODO: Need to add teleport functionality, list of sites to select
  
constraints:
  dist_other_gs: 3000000 # 3000 km for elevation min of around 10

start_epoch:
  year: 2025
  month: 4
  day: 1
  hour: 17
  minute: 23
  second: 40.69

end_epoch:
  year: 2025
  month: 4
  day: 2 #8
  hour: 17
  minute: 23
  second: 40.69

debug:
  verbose: True
  plot: False # TODO: maybe i don't need anymroe? or check
  wandb: True
  txtUpdate: False
  randseed: 0
